// Copyright 2019 dimakirol <your_email>

#ifndef INCLUDE_HEADER_HPP_
#define INCLUDE_HEADER_HPP_

#ifndef BOOST_BEAST_EXAMPLE_COMMON_ROOT_CERTIFICATES_HPP

#define BOOST_BEAST_EXAMPLE_COMMON_ROOT_CERTIFICATES_HPP

#endif // BOOST_BEAST_EXAMPLE_COMMON_ROOT_CERTIFICATES_HPP
#endif // INCLUDE_HEADER_HPP_
